#!/bin/bash

set -Cue

git submodule update --init --recursive

SCRIPT_DIR=$(cd $(dirname $0); pwd)

sudo apt update
sudo apt install -yq \
    build-essential \
    git \
    vim \
    tmux \
    fish \
    htop \
    cgdb  \
    neovim \
    curl

# fish
mkdir -p ~/.config/fish/functions

# fisherman
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman
${SCRIPT_DIR}/install.fish

# my-theme
ln -sf ${SCRIPT_DIR}/fish_prompt.fish ~/.config/fish/functions/fish_prompt.fish
ln -sf ${SCRIPT_DIR}/informative_git_prompt/__informative_git_prompt.fish ~/.config/fish/functions/__informative_git_prompt.fish

ln -sf ${SCRIPT_DIR}/fish_user_key_bindings.fish ~/.config/fish/functions/fish_user_key_bindings.fish

# git
ln -sf ${SCRIPT_DIR}/.gitconfig ~/.gitconfig

# vim
ln -sf ${SCRIPT_DIR}/.vimrc_minimum ~/.vimrc

#tmux
ln -sf ${SCRIPT_DIR}/.tmux.conf ~/.tmux.conf

# bash
cp ~/.bashrc ~/.bashrc.bak || true
echo "#-------my setting--------" >> ~/.bashrc
echo "source $SCRIPT_DIR/.bashrc" >> ~/.bashrc

ln -sf ${SCRIPT_DIR}/fzf ~/.fzf
~/.fzf/install --all
