[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
source ~/.config/nvim/plugins/rust.rc.vim
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
on_ft = ['rust', 'python']
build = 'coc#util#install()'
hook_add = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''

